### ISSUE TITLE
Clarification from user

### ISSUE THREAD

**Issue by Galkimron** [Forethought-Technologies/AutoChain#110]
Hey :)
when I use ConversationalAgent with PLANNING_PROMPT_TEMPLATE, the agent stopped because it was needed clarification from the user, but the agent already stopped/exit (the user can't give any input). could you please suggest simple why how to let the user insert it's answer in order to let the agent continue in the same running?

Thank you very much

**Comment by yyiilluu** [comment]
@Galkimron sorry for the late reply. i believe you run into this during workflow evaluation. i introduced a check from agent to verify if the problem has been solved or not. if user acknowledge the problem is solve, agent would stop before even planning for the next step. If you disable that `should_answer` check, agent by default will never stop, and you could limit the number of turns of conversation to k for your evaluation. Hopefully that solves your problem
